### ISSUE TITLE
page de contact

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#1]
Je t'avais envoyé ça, à ajouter à la fin de mon texte pour la page de contact:

Les services proposé sur notre site ne sont pas une liste exhaustive des demandes possibles.

Si vous n’avez pas trouvez la situation vous concernant, n’hésitez pas à nous contactez pour que nous trouvions une réponse adaptée à vos besoins.

**Comment by jean-philippe-p** [comment]
tu peux m'envoyer le text de cette page stp je le retrouve pas (en format html si possible)

**Comment by aurore-a** [comment]
Je ne crois pas en avoir fait.

Je vais essayer de t'en rédiger une avant la fin du week-end.

Il fallait ajouter un encadré de contact par contre

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by aurore-a** [comment]
pour le formulaire de contact, plus ouvert que ceux des page avec : 
- nom
-prénom
-ville
-code postal
-téléphone
-email
-message

**Comment by aurore-a** [comment]
`<p style="color: #3A5555;">Les services propos&eacute;s sur notre site ne sont pas une liste exhaustive des demandes possibles.
	<br>Si vous n&rsquo;avez pas trouvez la situation vous concernant, n&rsquo;h&eacute;sitez pas &agrave; nous contactez pour que nous trouvions une r&eacute;ponse adapt&eacute;e &agrave; vos besoins.</p>

<p>
	<br>
</p>

<p class="potter" style="color: #3A5555;">Vous pouvez nous contacter pour toute question, par t&eacute;l&eacute;phone, par mail ou par message via la boite de dialogue mise &agrave; votre disposition.</p>

<p style="color: #3A5555;">Nous prenons rapidement connaissance de votre demande et vous contactons rapidement pour &eacute;tablir avec vous une r&eacute;ponse efficace et adapt&eacute;e.</p>

<p>
	<br>
</p>

<p style="color:#474546">Si vous le souhaiter, nous pouvons &eacute;galement convenir d&rsquo;un rendez-vous directement dans nos bureaux.</p>`

**Comment by aurore-a** [comment]
<p style="color: #3A5555;">Les services propos&eacute;s sur notre site ne sont pas une liste exhaustive des demandes possibles.
	<br>Si vous n&rsquo;avez pas trouvez la situation vous concernant, n&rsquo;h&eacute;sitez pas &agrave; nous contactez pour que nous trouvions une r&eacute;ponse adapt&eacute;e &agrave; vos besoins.</p>

<p>
	<br>
</p>

<p class="potter" style="color: #3A5555;">Vous pouvez nous contacter pour toute question, par t&eacute;l&eacute;phone, par mail ou par message via la boite de dialogue mise &agrave; votre disposition.</p>

<p style="color: #3A5555;">Nous prenons rapidement connaissance de votre demande et vous contactons rapidement pour &eacute;tablir avec vous une r&eacute;ponse efficace et adapt&eacute;e.</p>

<p>
	<br>
</p>

<p style="color:#474546">Si vous le souhaiter, nous pouvons &eacute;galement convenir d&rsquo;un rendez-vous directement dans nos bureaux.</p>

**Comment by aurore-a** [comment]
[contact.docx](https://github.com/jean-philippe-p/callipolis/files/2041924/contact.docx)

C'est en html

**Comment by jean-philippe-p** [comment]
encore un document word
![1234931504682](https://user-images.githubusercontent.com/37634551/40580004-ba23149c-6135-11e8-8719-16da2903428f.jpg)

faut que tu prennes un editeur de texte tout simple sans formatage quand tu fais de l'html  
au pire utilise un éditeur de l'interface d'admin (sans sauvegarder) et tu copie/colle le text ici

**Comment by aurore-a** [comment]
mais j'ai essayé, mais ça ne laisse pas les balises !!

alors je te l'ai mis sur un document word mais il est en langage html arrête de râler ^^

**Comment by aurore-a** [comment]
J'ai revu la page, je la vois comme ça :) 

J'ai vu que celui ci aussi descendait mais du coup je ne sais pas si celui ci il vos mieux le laisser fixe ou changer un peu la mise en page. Qu'est-ce que tu en penses ?

![contact test](https://user-images.githubusercontent.com/39243112/40784149-106807ce-64e5-11e8-8d14-5ddd2c076fa6.png)

**Comment by aurore-a** [comment]
Je sais pas si tu le vois, mais j'ai un peu modifier les couleurs. Bigloute n'arrêtait pas de me dire que ça n'allait pas alors j'ai essayé autre chose... Et c'est la dernière modif de couleur ;) (enfin sauf si tout le monde critique encore... ) 

Je t'enverrai le nécessaire sur la issue correspondante !

**Comment by jean-philippe-p** [comment]
que vois-je ? un design complet ?
![plop](https://user-images.githubusercontent.com/37634551/40797651-40075b28-6509-11e8-94dd-c3995cf5e6ed.jpeg)
:laughing: 
tiens moi au jus quand tout le monde sera "ok" histoire que je bosse pas pour rien.
petites remarques perso :
- ça fait vide au milieu y a un blanc ("coordonnées" est peut etre trop excentré?)
- le texte en dessous du titre est peut etre un peu trop petit par rapport au reste
- les changements de couleurs de la police je trouve ça pas mal ça dynamise la page (c'est un peu moins monotone quoi)
- la couleur du formulaire c'est la meme que celle de la barre de menu ? c'est peut etre un peu trop sombre

voila, voila !
(tu remarqueras que j'utilise beaucoup "peut etre", je suis pas sur de ce que je dis, c'est peut etre pas pertinent, faut que tu vois avec d'autres gens)

**Comment by aurore-a** [comment]
![contact test_revu](https://user-images.githubusercontent.com/39243112/41038196-bbdf7088-6995-11e8-888a-e7e21628acec.png)

J'ai tranché :D

**Comment by aurore-a** [comment]
![icone_mail](https://user-images.githubusercontent.com/39243112/41038258-e069815a-6995-11e8-9b3c-4ec59cf6ee69.png)
![icone phone](https://user-images.githubusercontent.com/39243112/41038263-e480028c-6995-11e8-932c-9df46fd3000d.png)
![icone_adresse](https://user-images.githubusercontent.com/39243112/41038272-eb476664-6995-11e8-933c-3193ea1c49ff.png)

Voilà les icones :)

**Comment by aurore-a** [comment]
ah, et puis en cas de modification, tu pourras m'ajouter la page de contact dans l'admin ?

**Comment by jean-philippe-p** [comment]
ça y est, j'ai changé le design, par contre j'ai applicqué le style mais le résultat n'est pas comme celui de l'image

**Comment by aurore-a** [comment]
C'est bon pour celle ci donc on peut fermer l'issue.

Par contre, n'oublie pas de me le mettre en édition ;)

**Comment by jean-philippe-p** [comment]
ajouté
