### ISSUE TITLE
sous-titre "prostitution"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#10]
Il faudrait retirer la page de sous-titre.

Il n'y aura que l'encadré dans la page titre, du coup, si on peut enlever le "en savoir plus" pour ce sous-service uniquement, ça ferait plus propre (puisqu'il ne renvoie à rien ^^)

**Comment by jean-philippe-p** [comment]
yes je peux faire ça c'est pas dur mais pas sûr que ce soit une bonne idée, faut penser ergonomique, les gens vont se dire "y a un bug pourquoi ya pas de bouton ? je veux en savoir plus!" t'es sûr que y a rien a dire dessus ? tu pourrais dire par exemple que la prostitution en soit est pas condanable, mais la marchandise humaine l'est en citant des articles non ?

**Comment by aurore-a** [comment]
je vais y réfléchir ...
