### ISSUE TITLE
sous-titre "recherche d'adresse"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#11]
supprimer le sous-service et sa page, je ne vais pas proposer se service pour l'instant

**Comment by jean-philippe-p** [comment]
comme dit dans une autre issue tu pourra le faire toute seule dans pas longtemps

**Comment by jean-philippe-p** [comment]
c'est bon tu peux supprimer des servcies/sous-servcies dans l'admin dans l'ecran d'édition y a un bouton "delete" en bas a droite (en fait c'est pas une vrai suppression, je cache juste le service/sous-service en question, comme ça tu peux le récupérer si tu l'as supprimer pas erreur)
