### ISSUE TITLE
service "protection animale"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#12]
J'ai trouvé LA solution pour cette page ! 

Je vais mettre "protection animale" en service et "maltraitance sur les animaux" en sous-service, comme ça plus de problème de configuration.

Du coup, peux-tu ajouter une page de sous-service dans ce service ? Gracias !

**Comment by jean-philippe-p** [comment]
yes je vais faire en sorte que tu puisse ajouter/supprimer toi meme tes services/sous-service dans l'admin sans mon aide ;)

**Comment by jean-philippe-p** [comment]
c'est bon tu peux ajouter des servcies/sous-servcies dans l'admin avec le petit "+" dans les menu déroulant
