### ISSUE TITLE
Balise de renvoie à une page

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#13]
Je voudrais faire des renvoies de texte. Genre, si je parle d'un truc dans une page et que j'en parle de manière plus approfondie dans un autre service, est-ce qu'il y a une balise pour que je le mette sur le mot qui renverra à une autre page de mon site ?

**Comment by jean-philippe-p** [comment]
yep pour créer un lien dans l'éditeur t'as juste à éditer l'html (en appuyant sur `</>`) et mettre : 
```
<a href="la_cible_du_lien"> le text qui sera affiché et cliquable </a>
```

tu peux pointer n'importe où dans le site, par exemple si t'es dans le sous-service divorce (structure familiale) tu peux voir dans l'url de ton navigateur : 
```
https://www.callipolis-investigation.fr/alpha/services/9/sub-services/40
```
du coup si tu veux pointer vers cette page dans ton lien la cible sera :
```
/services/9/sub-services/40
```
(en d'autres mots faut enlever `https://www.callipolis-investigation.fr/alpha` et garder ce qui suit)  

ce qui donne au final : 
```
- `<a href="/services/9/sub-services/40"> divorce </a> `
```

**Comment by jean-philippe-p** [comment]
si t'y arrives pas hésite pas à me redemander, si t'y arrives tu pourras fermer cette issue stp ?

**Comment by jean-philippe-p** [comment]
je viens de voir qu'il y a un bug dans l'éditeur, il faut que tu reviennes à la vue sans les balises html sinon si tu sauvegardes, tes changements sont pas pris en compte
