### ISSUE TITLE
sous-titre "l'agence"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#14]
J'ai essayé d'éditer un truc joli pour les logos mais le tableau ne s'organise pas bien du tout sur le site 

preuve à l'appui !

version plate-forme : 
![image](https://user-images.githubusercontent.com/39243112/40492026-df72a72a-5f6f-11e8-880d-518e5bd2d3b0.png)

Version site : 
![image](https://user-images.githubusercontent.com/39243112/40492064-f8431474-5f6f-11e8-9ae5-12474895707b.png)

Ah aha aha pas du tout pareil !! ^^

Si tu peux faire un truc plus joli...

**Comment by jean-philippe-p** [comment]
ha ouai mais là tu fais un truc qu'était pas du tout prévu XD à la base c'était juste pour éditer du text, je vais voir ça devrait pas être trop dur de régler le pb

**Comment by aurore-a** [comment]
Okay ^^

Par contre, j'ai insérer un lien hypertexte sous chaque logo, ne les oublie pas.

**Comment by jean-philippe-p** [comment]
yep, par contre il faut que tu me donne le lien des images d'origine et vérifie qu'elles sont libre de droit (tu risques pas grand chose mais bon c'est mieux d'etre clean ;) )

**Comment by jean-philippe-p** [comment]
ça y est j'ai fais les modifs, le tableau s'affiche bien mais c'est pas les bonnes images, tu peux faire les modifs des liens directement dans l'html (en cliquant sur le bouton `</>`) mtn. 
par contre j'avais oublié de te le préciser mais il ne faut pas utiliser les outils images, video (tout type de fichier) de l'editeur. il faut directement éditer l'html pour ça

**Comment by aurore-a** [comment]
je n'ai pas de lien, je suis allée sur le site à chaque fois, j'ai cliqué sur leur logo et j'ai enregistré l'image.

J'ai mis dans mes info légales que les logos étaient à leur propriétaire, un truc comme ça, donc je ne sais pas si elles sont libre de droits mais ça devrait suffire non ?
