### ISSUE TITLE
titre service doublon

### ISSUE THREAD

**Issue by jean-philippe-p** [jean-philippe-p/callipolis#15]
@aurore-a t'as rajouté les titres des services dans le résumé, je suppose que c'est pour qu'on le voit dans l'écran d'accueil mais c'est pas la bonne méthode car sur l'écran du service y a un doublon. faut que tu l'enlèves de chaque résumé et si je me suis pas trompé et que tu veux l'afficher dans l'écran d'accueil, comfirme moi, il faut que ce soit moi qui le rajoute (et précise la taille et la police aussi)

**Comment by aurore-a** [comment]
Oui c'était pour ça !

Donc oui, rajoute le stp ??

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by aurore-a** [comment]
Police julius sans on taille 35px

**Comment by jean-philippe-p** [comment]
fait (mais la taille et 30 comme tu l'as défini dans une autre issue où je t'ai demandé de lister toutes les tailles des balises de titre)
