### ISSUE TITLE
tableau de logo

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#16]
J'ai inséré les logos comme une grande :D 

Je te disais dans l'autre issue que j'ai été récupéré les image directement sur les sites, donc j'ai fait pareil là, j'ai copié le lien de leur logo et je l'ai inséré.

J'ai ecrit dans mes mentions légales "Les liens avec d’autres sites web n’appartenant pas à Madame Alvy ne sont proposés que pour des raisons d’utilité. Les logos et marques cités appartiennent à leurs propriétaires respectifs." alors même si elles ne sont pas libres de droits ça devrait suffire non ?

Par contre, c'est possible de masquer les traits du tableau ?

**Comment by jean-philippe-p** [comment]
pour ce qui est des liens vers d'autres sites si je me trompe pas t'as pas à te justifier de leur utilisation.  

pour ce qui est du droit d'utilisation des images c'est pas si simple. en fait ça dépend de la license sous laquelle ils ont mis leurs images. il y a des licenses qui interdisent toute utilisation ou copie, y'en a qui le permettent mais ils faut citer l'ayant droit en disant que ça lui appartient, et d'autres qui te permettent de faire ce que tu veux... (il en existe plein de sorte).
donc cité d'où ça vient ca peut ne pas etre suffisant.  

imagine tu fais des copies du roi lion et tu les vends en mettant sur la boite "ça vient de chez disney".  
si tu te fais chopé et que tu dit au juge "non mais c'est bon j'ai cité Disney", il t'enverra chier :D 

pour ce qui est des bords du tableau oui c'est possible et ça donne ça : 
![tableau](https://user-images.githubusercontent.com/37634551/40863521-6f87efce-65f0-11e8-8dab-6e102fdc322f.png)

je préfère avec les bords perso, là je trouve que ça fait trop désordonné

**Comment by jean-philippe-p** [comment]
après même s'il autorisent pas l'utilisation de leurs images, c'est 4 pauvres logos qui renvoient sur leur site en plus. donc en pratique ils te feront pas chier (faut deja qu'ils aient connaissance de ton existence). mais bon sache qu'il y a un risque meme s'il est infime

**Comment by aurore-a** [comment]
J'ai vérifié, effectivement, j'ai pas le droit !! Ils ont tous écrit qu'il faut avoir l'autorisation. 

La matmut va plus loin, ils écrivent carrément "Tout lien vers le site matmut.fr est soumis à une autorisation préalable de la Matmut" 

Bon, qu'est-ce que tu en penses ...? Je vire carrément les logo ? je vais quand même pas m'emmerder à leur faire des courriers ...

**Comment by jean-philippe-p** [comment]
je peux pas décider à ta place, c'est toi qui vois.  
tu peux peut etre leur envoyer un mail plutot qu'on courier, c'est moins contraignant, et tu mets le lien https://www.callipolis-investigation.fr/alpha/introduces/1 dans le mail  
par contre faudra peut etre que tu enlèves leur lien et leur image sur la page avant d'envoyer le mail (sinon ils risquent de déjà te faire chier ) et tu mets en piece jointe l'image que j'ai uploadé ici pour montrer à quoi ça ressemblera.

**Comment by aurore-a** [comment]
Bon, j'ai finalement résolu le problème pour l'instant...

Moins beau, mais moins chiant, on verra plus tard si je m'y colle à nouveau.

Donc pour l'instant je vais mettre ça à la place : 
![cnaps 2](https://user-images.githubusercontent.com/39243112/41039013-6ac2f87a-6998-11e8-85d6-be639a59c658.png)
![cnil 2](https://user-images.githubusercontent.com/39243112/41039019-6e698a16-6998-11e8-9b47-abcfad628cd1.png)
![matmut 2](https://user-images.githubusercontent.com/39243112/41039030-7634bba8-6998-11e8-9c2d-ecffa96320af.png)
![unimes 2](https://user-images.githubusercontent.com/39243112/41039039-7ce7e416-6998-11e8-8acf-67d592d8f8fa.png)

Tu penses que ça ira ?

**Comment by jean-philippe-p** [comment]
j'ai fait le changement
