### ISSUE TITLE
page d'acceuil

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#17]
On fait comment pour les "phrases choc" de l'écran d’accueil ?

Je te les envoie ou tu me le mets aussi en éditeur ?

**Comment by jean-philippe-p** [comment]
j'avais completement zappé ce truc :D ouai je vais te le rajouter dans l'admin.  
faut que tu m'envoies l'image de fond aussi d'ailleurs

**Comment by aurore-a** [comment]
J'essaie de trouver plusieurs images qui s'accordent avec les différentes phrases, mais c'est pas encore fini, je t'envoie ça dès que j'ai tout sélectionné.

**Comment by aurore-a** [comment]
![1](https://user-images.githubusercontent.com/39243112/41419241-d961539e-6ff1-11e8-8d57-c31dcc0b89e2.jpg)

**Comment by aurore-a** [comment]
![2](https://user-images.githubusercontent.com/39243112/41419264-e91de5cc-6ff1-11e8-8ad2-846aa7797148.jpg)

**Comment by aurore-a** [comment]
![6](https://user-images.githubusercontent.com/39243112/41419303-fd27ea18-6ff1-11e8-9c63-aedda7295392.jpg)

**Comment by aurore-a** [comment]
![3](https://user-images.githubusercontent.com/39243112/41419345-14b5c308-6ff2-11e8-91a6-ce8a0a363d80.jpg)

**Comment by aurore-a** [comment]
![4](https://user-images.githubusercontent.com/39243112/41419368-1ef9b4be-6ff2-11e8-90da-a31f34e3c53d.jpg)

**Comment by aurore-a** [comment]
![5](https://user-images.githubusercontent.com/39243112/41419393-2e999d26-6ff2-11e8-8073-74155134927c.jpg)

**Comment by aurore-a** [comment]
![9](https://user-images.githubusercontent.com/39243112/41419415-405137a4-6ff2-11e8-9903-38da8728a1dc.jpg)

**Comment by aurore-a** [comment]
![7](https://user-images.githubusercontent.com/39243112/41419443-570bab50-6ff2-11e8-88cc-529c27153bdb.jpg)

**Comment by aurore-a** [comment]
Voilà les huit photos sélectionnées, à placer dans cet ordre là

Est-ce que tu peux faire quelque chose pour la taille ou je le fais moi ?

**Comment by jean-philippe-p** [comment]
faudrait que tu découpes toute les images avec le meme rapport de 2.75 (largeur 2.75 fois plus grand que la hauteur), c'est le rapport qu'il y a pour l'image avec l'oeil.

**Comment by jean-philippe-p** [comment]
dans l'admin tu pourras uploader tes images au niveau de carousel dès que je rentre chez moi pour je fasse la mise en ligne du nouveau code

**Comment by jean-philippe-p** [comment]
c'est fait
