### ISSUE TITLE
duplication résumé sous-service

### ISSUE THREAD

**Issue by jean-philippe-p** [jean-philippe-p/callipolis#18]
je viens de voir que tu as aussi dupliqué les résumés des sous-services dans le texte "principal".  
contrairement au services (où tu avais dupliqué les titres) c'est pas trop grave ça se voit pas mais vaut mieux pas faire comme ça.  
car là si t'as une modification à faire dans le résumé il va falloir que tu le fasses à deux endroits differents et y a des chance que tu n'y penses pas.

du coup si tu veux mettre le résumé dans le texte principal <b>et que le style est le meme dans tous les sous services</b>, il vaudrait mieux que tu enlève toutes les duplications que tu a fait et que je le rajoute de mon coté.

**Comment by aurore-a** [comment]
Effectivement !

J'ai mis tous les résumés en : 

< p style="font-family: 'Open Sans', sans-serif;font-size: 17px; text-align: center; color:#666666;" > 

Et, plus ça va, plus je trouve que le résumé du Service est quand même un peu imposant peut-être par rapport aux autres éléments de texte dans la page de sous-service.
C'est possible de le diminuer là (à la taille du corps de texte donc 17px) et de garder sa taille dans la page de service ?

**Comment by jean-philippe-p** [comment]
ça y est le résumé du sous service s'affiche automatiquement dans la page de sous-service.  
j'ai supprimé tous les doublons dans le text.  
et pour ce qui est de la taille du texte je l'ai pas changé, à mon avis c'est une mauvaise idée de changer la police sur le même élément de la page en fonction du contenu qu'il y a plus bas.  
Soit je mets tout le temps an 17px soit faut revoir la mise en page du reste

**Comment by aurore-a** [comment]
Mais le "resum titre" est plus gros que 17 px dans la page "service" 

il me semble que je te l'avais fait mettre en Merriweather 20px , mais finalement, il vaut mieux le mettre en taille standart donc 17 px, pour qu'il soit à la même taille que le texte .

**Comment by jean-philippe-p** [comment]
c fait
