### ISSUE TITLE
ecriture

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#2]
Titre : Julius Sans One en 55px

sous-titre : Merriweather Sans Bold en 28 px

corps de texte : Open sans Regular en 18 px

résume : Merriweather Sans Regular en 20 px

pour "potter" : Open Sans Extra-bold en 20 px

pour  "qui sommes nous"  --> les "titres" en  Julius Sans One en 55px et le corps de texte en  Open sans Regular en 18 px aussi 

Pour la police sur les autre éléments, met Open Sans en regular, je verrai plus tard. 

https://fonts.google.com/specimen/Open+Sans

https://fonts.google.com/specimen/Merriweather+Sans?selection.family=Merriweather+Sans

https://fonts.google.com/specimen/Julius+Sans+One?selection.family=Julius+Sans+One

**Comment by aurore-a** [comment]
j'ai inséré plusieurs balise en plus de "potter"

<h5> : utilisé pour des titres dans le corps de texte ; police : Merriweather Sans Light 22px
<h6> : utilisé pour les titre dans les infos légales et mentions légales ; police : Julius Sans One 40px en centré

**Comment by aurore-a** [comment]
h5 la première
h6 la deuxième 

ça a disparu à l'envoie ^^

**Comment by jean-philippe-p** [comment]
les titres c'est un peu trop à la waneguen-bistouflaille il faudrait que tu me fasses une hierarchie des titres pour être cohérent dans toooouuuut le site de \<h1>(plus grand) à  \<h6>(plus petit)  (t'es pas obligé de tous les utilisés) en précisant la taille et la police et où les mettre.
pour l'instant on a :
 \<h1> qui est utilisé pour : 
- le titre du service dans l'ecran du service ou du sous service 
- le titre du formulaire "CONTACT" (l'encadré pas l'écran)
- le titre dans "qui somme nous"

\<h2> qui est utilisé pour : 
- le titre des sous services dans l'ecran service

\<h3> qui est utilisé pour : 
- le titre du sous service dans l'ecran sous service

**Comment by jean-philippe-p** [comment]
petites precisions:
- tu pourras aussi les mettres où tu veux en éditant les textes mais le rendu sera pas forcement fidèle, le style ne sera apliqué que sur le site un fois sauvegardé.
- les titres peuvent etre plus petits que le texte, c'est pas souvent utilisé mais c'est possible
- le style d'un titre n'est pas figé, les tailles et police que tu va me donner seront en fait par défaut mais pour des cas particuliers (dans le texte que tu édite par exemple) on pourra toujours ajuster

**Comment by aurore-a** [comment]
alors, ça donne : 

< h1 > Julius Sans One en 55px pour : 

- le titre du service dans l'ecran du service ou du sous service
- le titre du formulaire "CONTACT" (l'encadré pas l'écran)
- le titre dans "qui somme nous"

< h2 > Julius Sans One 40px en centré qui est utilisé pour :

- les titre dans les infos légales et mentions légales

< h3 > Julius Sans One 30px en centré qui est utilisé pour :

- Les titre de service dans l'écran d'acceuil

< h4 > Merriweather Sans Bold en 28 px pour :

- le titre du sous service dans l'ecran sous service

< h5 > Merriweather Sans Bold 25px

- le titre des sous services dans l'ecran service

< h6> Merriweather Sans Light 22px pour : 

-  les titres dans le corps de texte


Ce qui nous laisse : 

- < "potter" > : Open Sans Extra-bold en 20 px

- corps de texte : Open sans Regular en 17 px

- Résumé du service dans la page de sous-service : Merriweather Sans Regular en 20 px


Je crois que je n'ai rien oublié

**Comment by jean-philippe-p** [comment]
j'ai tout fais sauf potter. j'arrive pas à appliquer la class dans le texte éditable ça me pète les couilles!
du coup ce que tu peux faire au lieu de mettre `class="potter"` tu peux mettre `style="font-family: 'Open Sans', sans-serif;font-size: 20px;"` dans les balises html (si y a deja un style existant dans la balise il faut que tu complete celui qui existe deja et pas rajouter un deuxieme `"style=..."`)
