### ISSUE TITLE
icone onglet

### ISSUE THREAD

**Issue by jean-philippe-p** [jean-philippe-p/callipolis#21]
il faudrait que tu m'envoies un tout petit icone pour que je le mette au niveau de l'onglet : 

![icone](https://user-images.githubusercontent.com/37634551/40936198-e0a8e572-683a-11e8-881c-9cfecc78c55b.png)

**Comment by aurore-a** [comment]
J'avais pas vu !

**Comment by aurore-a** [comment]
c'est star wars le dessin ?? ahahaha

**Comment by aurore-a** [comment]
![mini logo](https://user-images.githubusercontent.com/39243112/41038807-bdd21a88-6997-11e8-9bfd-03a6204d823a.jpg)

Comme ça ça ira ?

**Comment by jean-philippe-p** [comment]
je l'ai changé mais il vaudrait mieux une image png avec le fond transparent

**Comment by aurore-a** [comment]
Je l'ai demandé à Christelle. Dès qu'elle me l'aura fait je te le donne.

**Comment by aurore-a** [comment]
![mini logo transparent](https://user-images.githubusercontent.com/39243112/41508231-95caba56-7241-11e8-881e-644290c3fb2b.png)

**Comment by jean-philippe-p** [comment]
fait
