### ISSUE TITLE
Mise en page

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#22]
Regarde ce beau design que je t'ai préparé !!! :D 

J'ai fait quelques petites modifs, genre : 

- sur le pied de page 

écriture pied de page plus petite, 12 px
pied de page moins haut
modification du texte de pied de page
sur l'en-tête

- sur l'en-tête

modification texte en-tête
en tête haute
logo plus petit 

- page

J'ai fait un décallage des services, je trouve ça plus sympa
J'ai essayé de mettre les photos voir comment ça fait mais je me rend pas compte en fait.

**Comment by aurore-a** [comment]
![page acceuil](https://user-images.githubusercontent.com/39243112/41051262-dc62923e-69b5-11e8-8cd2-cff7f75e95c0.png)

**Comment by aurore-a** [comment]
![page de sous-service](https://user-images.githubusercontent.com/39243112/41051283-f38d48dc-69b5-11e8-8efc-aa879a66bf5b.png)

**Comment by aurore-a** [comment]
Il n'y a pas la page de service parce que je n'ai pas encore jugé pour le placement des encadré ;)

Et ne fait pas attention à l'encadré "article et important" je ne l'ai pas reproduit, le tiens est bien mieux, mais j'ai changé les couleurs

**Comment by aurore-a** [comment]
![icon-157358_640](https://user-images.githubusercontent.com/39243112/41202819-eec61cf4-6cce-11e8-8133-481d5069f46b.png)
![letter-147563_640](https://user-images.githubusercontent.com/39243112/41202820-f2f65960-6cce-11e8-8c5f-ebdb3bcb1131.png)

Voilà pour les icones de l'en-tête en transparent :)

**Comment by aurore-a** [comment]
l'encadré "tarif en plus petit, fond gris, renvoie à la page de tarif

**Comment by aurore-a** [comment]
renvoie à la page d'acceuil sur le logo

**Comment by aurore-a** [comment]
TITRE de "qui sommes-nous?" en centré

**Comment by aurore-a** [comment]
Texte en-tête : 

Agence de Recherches Privées - Détective privé

Intervention 7 jours / 7 

06 68 65 91 26                           contact@callipolis-investigation.fr

**Comment by aurore-a** [comment]
texte pied de page (à droite) : 

Devis gratuits

Intervention 7 jours / 7
en Occitanie et dans toute la France

**Comment by aurore-a** [comment]
Enlever le cadre du tableau de "logo"

**Comment by jean-philippe-p** [comment]
j'ai fais la plupart des truc sauf la tailles des elements il faut que tu me dise un truc plus précis que "plus petit" je peux rien faire avec ça.  
pour la couleur de tarif "gris" c'est pas assez précis, j'ai mis la meme couleur que l'entête, je sais pas trop si c'est gris :D  
et les logo du téléphone et de l'email sont noir, il en faudrait des blancs

**Comment by aurore-a** [comment]
ahaha bien tenté mais c'est bleu ça ^^

le même gris que pour les "articles inportant" donc gris clair    #d8d8d8	216, 216, 216

**Comment by aurore-a** [comment]
EN PLUS

J'ai oublié de te dire l'autre jour, il faudrait laissé un peu plus d'espace entre le titre du sous service et le résume sous service dans la page de sous service stp 
Un saut de ligne disons

**Comment by jean-philippe-p** [comment]
j'ai fait en sort que le bouton tarif colle avec le pied de page mais ça fait bizarre je trouve faudrait peut etre une autre couleur sur toute la bande comme avant

**Comment by aurore-a** [comment]
Prend ton ordi demain, on réglera les derniers petits détails ensemble ce weekend  :)

**Comment by jean-philippe-p** [comment]
encadré contact ajuster pour chrome
police 15px
bouton police 14px
footer 70px

**Comment by jean-philippe-p** [comment]
fait!
j'en ai profité pour rendre le site compatible sur tablette/smartphone, ça s'affiche beaucoup mieux ;)
