### ISSUE TITLE
Pied de page

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#23]
Je voudrais réduire la taille de l'écriture du pied de page à 12 

Du coup, pour "réduire" la hauteur de cette partie, il faut le faire en fonction de la place qu'il y a et qui est inoccupée. 

Avant réduction : 

![image](https://user-images.githubusercontent.com/39243112/41353933-eeda453e-6f1d-11e8-9be8-7e1159d9a3fd.png)

après réduction : 

![image](https://user-images.githubusercontent.com/39243112/41353963-00ed39de-6f1e-11e8-82a7-26bdc70cd47a.png)

Bon, je ne me rend pas compte de la taille que ça représente en réalité sur paint c'est pas pareil le police. 
Disons que je les trouve un peu imposant donc je voudrais essayer de réduire un peu

Là sur le truc, j'ai : 

- diminué le logo de 20% (sur paint en tout cas) 

- diminué la taille de l'écriture en pied de page (je pense environ 12 ira) 

- resserré le texte en haut de page sans diminuer la taille

- diminué la hauteur du cadre de pied de page et haut de page 

Qu'est-ce que tu en penses ?

**Comment by aurore-a** [comment]
ah, et j'ai enlevé le petit cercle pour tweeter, on peut l'enlever en haut et en bas

**Comment by jean-philippe-p** [comment]
- j'ai baissé la hauteur du haut de page et du pied de page de 20% 
- j'ai mis 15px pour la taille de police du haut de page (12 ça faisait trop petit)
- j'ai mis 12px pour la taille de police du pied de page
