### ISSUE TITLE
Figure à insérer

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#24]
Il faut me mettre ce tableau dans le "article" du sous titre "maltraitances et violences" du titre "protection de l'enfance" 
![image1](https://user-images.githubusercontent.com/39243112/41508192-e3fede7e-7240-11e8-8700-8baa61ac83bd.png)

**Comment by jean-philippe-p** [comment]
j'ai totalement changé la gestion des articles comme on en avait parlé : 
- tu peux créer des articles dans l'onglet articles dans l'admin
- les articles précédemment créés peuvent être lié  aux sous services et aux différents "qui sommes nous ?" dans leurs propres écrans d'édition

pour l'image tableau encore une fois je déconseil, ça va être dégueux, tu peux construire ton propre tableau en éditant le texte de l'article concerné, ce sera plus long, mais tu pourras le customiser comme tu veux (police, couleur de police, couleur de fond)
