### ISSUE TITLE
Section "article"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#29]
Il y a un problème avec la façon dont tu m'as mis le truc

ça écrit automatiquement "article" alors que c'est "Article", "Articles" ou "Cour de ...." donc c'est pas bon, il faudrait retirer le "article" qui s'impose automatiquement.

- Pour la police du nom de l'article : identique au texte
- couleur de police : Gris foncé			#2f2d2e			47, 45, 46
- fond : gris clair 			#d8d8d8			216, 216, 216

**Comment by aurore-a** [comment]
Il y a aussi un bug sur l'édition des articles. Je viens d'en faire deux, une fois édités, je n'ai pas pu les modifier

ça me fait une page vierge 

![image](https://user-images.githubusercontent.com/39243112/41974417-338c3d72-7a18-11e8-9419-212b5eff5e8b.png)

**Comment by jean-philippe-p** [comment]
j'avais pas prévu que tu puisses mettre des phrases entières, dans mon idée tu mettais que le numéro de l'article et c'est pour ça que je préfixais par "article ".

j'ai tout corrigé par contre avec le nouveau style on voit pas trop que c'est cliquable je trouve

**Comment by aurore-a** [comment]
Et si on met une petite flèche après le nom, genre ça >
Qu'est-ce que tu en penses ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by jean-philippe-p** [comment]
c'est fais j'ai mis ">>" pour rappeler les boutons "en savoir plus"
