### ISSUE TITLE
couleurs site

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#3]
Violet #2F0B3A

Rose #B40431

Rouge #B40404

Orange #FF8000 

Jaune #D7DF01

Vert #04B404

Bleu vert #088A85

Bleu #0B0B61

==>  Pour chaque service «titre», une couleur de pastille, le titre est de la couleur de la pastille en page d’accueil

Fond bulle de contact #3A5555

texte contact #A3EEBA

Fond haut de page #8BBF9B

Ecriture haut de page #1B1023

Fond de page blanc

Fond barre de menu #3A5555

Fond bulle «en savoir plus» #266B6B

Fond bulle «articles et «important» #798C91

Texte bulle «articles» et «important #1B1023

Fond pied de page #1B1023

Sous titre dans page #1B1023

Titre dans page #586B6B

Resume titre dans page #65656A

Resume sous titre dans page #373737

Resume sous titre et resume titre dans bulle #1B1023

Texte barre de menu #BDBDBD

Texte pied de page #BDBDBD

Je ne t'ai pas remis les couleurs incorporées en corps de texte, mais si tu en as besoin, elles sont sur la dernière version html que je t'ai envoyé samedi je crois ;)

**Comment by jean-philippe-p** [comment]
@aurore-a c'est quoi que t'appelles bulle en fait ? l'encadré, le bouton ? tu pourrais remplacé par ces termes stp ça sera plus comprehensible pour moi

**Comment by aurore-a** [comment]
Violet #2F0B3A

Rose #B40431

Rouge #B40404

Orange #FF8000

Jaune #D7DF01

Vert #04B404

Bleu vert #088A85

Bleu #0B0B61

==> Pour chaque service «titre», une couleur de pastille, le titre est de la couleur de la pastille en page d’accueil

Fond encadré de contact #3A5555

texte contact #A3EEBA

Fond haut de page #8BBF9B

Ecriture haut de page #1B1023

Fond de page blanc

Fond barre de menu #3A5555

Fond bouton «en savoir plus» #266B6B

Fond encadrés «articles et «important» #798C91

Texte dans les encadrés «articles» et «important #1B1023

Fond pied de page #1B1023

Sous titre dans page #1B1023

Titre dans page #586B6B

Resume titre dans page #65656A

Resume sous titre dans page #373737

Resume sous titre et resume titre dans encadré (niveau accueil pour les resum titre ; niveau services pour les resum sous-titre) #1B1023

Texte barre de menu #BDBDBD

Texte pied de page #BDBDBD

**Comment by jean-philippe-p** [comment]
bon normalement y a tout qu'est a peu près fais. par contre je comprend pas 
- titre et sous titre ça veut dire quoi et dans quel context ? sous titre = sous titre service ? Resume sous titre = ? dans page = ?

est ce que tu peux refaire une liste avec ce qu'il reste a faire niveau couleur (t'as peut etre d'autres couleurs que t'avais pas avant) en etant plus clair sur les éléments en question

**Comment by aurore-a** [comment]
Une chance que mon livre soit captivant ! ??

Ne fait pas les couleurs, je vais tout te renvoyer !


Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by aurore-a** [comment]
- gris clair 			#d8d8d8			216, 216, 216

Fond «articles et important»
Écriture pied de page

- Bleu vert clair  		#75e5e5			117, 229, 229

Écriture «Téléphone» «email» «informations» etc.. du formulaire de contact (pas le Titre «contact» qui reste en couleur < h1 > )

- Bleu vert foncé		#01a9a9				1, 169, 169

Fond en-tête

- Bleu vert 			#30b8b8			48, 184, 184

encadré "en savoir plus" dans page de service
< h1 >
< h2 >
< h3 >


- Gris foncé			#2f2d2e			47, 45, 46

fond barre de menu
fond pied de page
fond encadré "contact"
Texte «resume titre» dans page de sous-service et page de service
Texte «en savoirs plus»


- Jaune				#f3ab01				243, 171, 1

< h4 >
< h5 >
Encadré «en savoir plus» dans page accueil

- Noir				#000000			0, 0, 0

écriture haut de page "Agence de Recherches Privée - Détective Privé"
corps de texte 

- Blanc				#ffffff			255, 255, 255

Texte haut de page «intervention 7 jours / 7»
«06 68 65 91 26  contact@callipolis-investigation.fr»

**Comment by aurore-a** [comment]
BON !! 

J'ai cru que je ne m'en sortirai JAMAIS ! 

A priori j'ai rien oublié mais bon... à force je ne sais plus ce que je fais ou non ^^

**Comment by jean-philippe-p** [comment]
ça y est j'ai fait les changement mais tu as oublié l'encadré du tarif (je l'ai laissé à la meme couleur)

**Comment by aurore-a** [comment]
- Gris foncé	#2f2d2e	47, 45, 46

Pour le texte "article et important" 

"articles" et "important (que les deux mots) en julius ( je ne sais pas si c'est le cas)

ah, et tu as écrit "Imporant" au lieu de "Important" ^^

- Jaune	#f3ab01	243, 171, 1

Encadré "envoyer" du formulaire de contact

**Comment by jean-philippe-p** [comment]
fait! par contre les logos importants et articles sont blancs du coup ça fait bizarre
