### ISSUE TITLE
Problème carousel

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#30]
J'ai ajouté une image (la troisième) en oubliant de mettre un titre. Du coup ça a ajouté la photo mais impossible de la retrouver sur l'admin...

Désolé, je savais pas. C'est récupérable ?

**Comment by aurore-a** [comment]
sinon pour celui-ci j'ai rien à ajouté, j'ai tout mis bien. Comment tu trouves ?

**Comment by jean-philippe-p** [comment]
ouai tkt c'était un petit défault en fait l'élément était bien dans la liste mais n'avais rien dedans donc zéro pixels de hauteurs et du coup invisible. j'ai corrigé ça en mettant "pas de titre" si y a pas... de titre.

par contre les "***" dans le titre et le reste dans le texte c'est carrément moche XD  
vaut mieux : 
- soit tout mettre dans le texte et rien dans le titre  
- soit mettre la phrase dans le titre (et pas dans le text) et moi j'ajoute automatiquement les "***" en haut et en bas (et il faut que tu me donne le style que tu veux si besoin (pour l'instant les titres du carousel sont en `h3` avec le style par default de tous les `h3`))

**Comment by aurore-a** [comment]
j'ai mis * * * parce que si je ne mettais pas de titre je n'avais plus les images XD

Mais en même temps, ça ne me choque pas plus que ça

**Comment by jean-philippe-p** [comment]
ba c'est tout de meme pas terrible pour retrouver ton image dans la barre de menu (dans l'admin)  
et pense à mon petit coeur de développeur perfectionniste, j'ai manqué de tourner de l'oeil en voyant ça :D

**Comment by jean-philippe-p** [comment]
je viens de voir que c'est effectivement pas bon de faire comme c'est actuellement, lorsqu'on est sur des petits écran, la taille de la police reste la meme et le texte est compètement décentré voir on le voit plus

**Comment by aurore-a** [comment]
On doit faire comment du coup ?


Tant qu'on est aux problèmes sur petits écran, ça bug sur téléphone


[Image]




Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by jean-philippe-p** [comment]
je m'en occupe tkt

et pour l'autre probleme l'image s'affiche pas mais ouvre une autre issue ça sera mieux

**Comment by jean-philippe-p** [comment]
ça y est j'ai fait les changement :  
le titre n'est plus affiché sur le site  
dans l'admin tu peux modifier le placement du texte par rapport à l'image avec les differentes marges (et le résultat temporaire est visible sur l'image)
