### ISSUE TITLE
section article problème 2.0

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#32]
Il y a un beug, certains articles ne sont pas consultables... -_-
Ils sont dans le liste mais je ne peux plus les éditer... J'ai remarqué ça parce que je voulais vérifier les articles quand j'avais deux fois le même mais impossible.

**Comment by aurore-a** [comment]
J'avais fait tous les articles et il y a un autre beug :'(

Ça le fait au moins pour "arret de travail abusif" dans le service "pro et entreprises", les articles ne ce sont pas mis et quand j'essaie de remettre dans l'éditeur, il ne veut plus ajouter d'articles

**Comment by jean-philippe-p** [comment]
bon c'est trop la merde ces articles! c'est pas du tout comme j'avais prévu, c'est des phrases à ralonge pour identifier l'article, c'est pas bon (j'avais limité la taille pour économisé la mémoire, c'est pour ça que ça bug (et pas beug :p )) mais bon c'est probablement de ma faute je t'avais pas expliqué.

je vais changé le fonctionnement du truc. faudra que tu mettes uniquement le nécessaire par exemple pour les articles du code pénal tu mettras que le numero et le reste sera automatiquement ajouté

j'ai identifié les types suivant qui se répètent : 
- Article `numero` du code civil
- Article `numero` du code pénal
- Article `numero` du code des assurances
- Article `numero` du code du travail
- Article `numero` du code des assurances
- Chambre sociale de la cour de cassation, arrêt du `date`, n°`numero`
- Conseil d'État, Section du Contentieux,  `date`, `numero`
- Cour de Cassation, Chambre criminelle, du `date`,  `numero`
- Cour de cassation, civile, Chambre civile 1,  `date`,  `numero`
- Cour de cassation, civile, Chambre civile 2,  `date`,  `numero`
- Cour de cassation, civile, Chambre sociale, `date`,  `numero`
- Cour de cassation, criminelle, Chambre criminelle, `date`,  `numero` (je suppose que c'est la meme que la huitième, si oui je garde lequel ?)
- Cour de Cassation, Première chambre civile, du `date`,  `numero`
- Directive (UE) `numero` du Parlement européen et du Conseil du `date`
- Jurisprudence de la Cour de cassation, civile, Chambre sociale, `date`,  `numero`
- Loi n°`numero` du  `date`
- Réforme du  `date` (y a pas un nom ou un numero ?)
- La prestation compensatoire (y a pas un nom ou un numero de loi, article... ?)

comme ça lors de la saisie d'un article t'auras plus qu'a saisir ce qui est dans `  ` et le reste sera mis automatiquement
ça sera beaucoup plus propre, plus facile à saisir et a retrouver dans la bare de menu

j'essaie de te faire ça ce soir

**Comment by jean-philippe-p** [comment]
faudra que tu refasses les liens des articles sur les sous-services suivants (quand j'aurais fini) : 
- Harcèlement au travail
- Abus de confiance
- Arrêt de travail abusif

**Comment by jean-philippe-p** [comment]
ça y'est j'ai fait les changements
