### ISSUE TITLE
bUg

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#33]
J'ai relevés des bugs, ou des beugs, comme on veut ;)

- Sur le sous service "infidélité", l'encadré de contact ne reste pas à sa place. Il descend sur la partie "important" et quand on remonte, il passe sur le texte resum titre aussi.

- Plusieurs fois, le temps pour que la page s'affiche met quelques secondes et ça affiche la page de service au lieu de la page de sous service que je demande. Je ne sais pas pourquoi ^^

- Pas un bug mais une petite correction (un détail, je suis tatillon) Code pénal, Code civil, etc. avec un C majuscule stp

**Comment by jean-philippe-p** [comment]
fait
