### ISSUE TITLE
réseaux sociaux

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#34]
Bon, désolé... J'avais pas l'intention d'utiliser twitter mais Marie-Pierre a insisté alors j'ai capitulé...

du coup, il faudrait le remettre dans les petits boutons ... :D 

Facebook : https://www.facebook.com/CallipolisInvestigation/

Twitter : https://twitter.com/Aurore_Alvy

LinkedIn : www.linkedin.com/in/aurore-alvy

Pour Google+ on verra plus tard...

**Comment by jean-philippe-p** [comment]
fait
