### ISSUE TITLE
mise en page smartphone

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#35]
![36516130_10216259275904161_9072100501255880704_n](https://user-images.githubusercontent.com/39243112/42239487-5f833912-7f04-11e8-8fe5-df4ff1db5a14.jpg)

ça donne ça sur téléphone. Les encadrés de droite l'écriture est coupée.

**Comment by aurore-a** [comment]
![36615996_10215617883495692_2711602519720591360_n](https://user-images.githubusercontent.com/39243112/42239651-d9da92be-7f04-11e8-9fe1-0f7b6368e784.png)

Pour les encadrés de gauche c'est l'image qui est coupé, ce qui n'est pas très esthétique mais qui est moins grave ^^

**Comment by aurore-a** [comment]
Pour la page qui présente les sous services c'est bon, mais sur les pages avec tout le texte (sous services) il y a un beug sur l'encadré "tarif" qui vient se foutre sur les articles

**Comment by jean-philippe-p** [comment]
lorsque l'ecran est petit, je te propose de mettre les images au dessus et non a coté (comme dans l'écran service qui liste les sous-services) comme ça le texte prendra toute la largeur ce sera beaucoup plus lisible. t'es ok ?

**Comment by jean-philippe-p** [comment]
(et j'ai corrigé le bouton tarif)

**Comment by aurore-a** [comment]
oui okay, si c'est mieux moi ça me va ! :)

**Comment by jean-philippe-p** [comment]
fait
