### ISSUE TITLE
contact site

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#36]
j'ai appuyé sur "sauvegarde" dans l'admin, là où il y a les message que laissent les gens sur le site.

C'est quoi? 

ça sauvegarde ou ?

**Comment by aurore-a** [comment]
ah, et j'ai besoin de pouvoir les supprimer aussi, j'avais pas pensé... Rapport aux obligations de la CNIL en matière de conservation des données

**Comment by jean-philippe-p** [comment]
ça sauvegarde le fait que tu l'ai traité ou non.  
et je te rajoute la suppression dans la journée

**Comment by aurore-a** [comment]
gracias !
;)

**Comment by jean-philippe-p** [comment]
ça y est. j'ai aussi un petit peu amélioré l'affichage. et j'ai aussi ajouté un filtre pour que tu puisse retrouver un client spécifique avec son téléphone ou son email
