### ISSUE TITLE
attennnnnd !!!

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#37]
ahaha, tu l'as fermé trop vite l'autre issue !

je regarde le site sur smartphone là et les phrases du carousel sont toujours coupées
Je pense que c'est parce que la police est trop grosse pour l'image à ce format

**Comment by aurore-a** [comment]
WAIT !

autre bug non signalé, celui sur la page de contact du site !

ça coupe l'adresse mail et le texte sort de l'encadré 

![36675028_10215622815458988_1118979816880603136_n](https://user-images.githubusercontent.com/39243112/42275249-fb5d3e38-7f8f-11e8-9a12-effbea32fe98.png)

**Comment by jean-philippe-p** [comment]
tout corrigé

**Comment by aurore-a** [comment]
ce matin c'était toujours pareil. Je ré-ouvre l'issue au cas où, je ne sais pas si la mise à jour prend son temps où si c'est parce que ça n'a pas marché.

**Comment by jean-philippe-p** [comment]
a fuck ça marche sur l'ordi avec une fenêtre toute petite

**Comment by jean-philippe-p** [comment]
bon ça devrait etre bon maintenant, c'était une sombre histoire de ratio de pixel uniquement sur smartphone
