### ISSUE TITLE
Page d'acceuil

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#4]
![acceuil site](https://user-images.githubusercontent.com/39243112/39999386-4b87cf7e-5789-11e8-8afe-ba853a0eed9c.png)

Voilà le genre pour le pied de page et les infos à mettre en haut de page. 

Pour la police, je ne sais pas encore, je préfère le faire après donc pour l'instant disons Open Sans Regular 18 px, on règlera ça après.

**Comment by jean-philippe-p** [comment]
- j'ai rajouté les informations dans le haut de page
- j'ai rajouté le pied de page avec les liens vers mentions/infos légales (qui sont éditables dans l'admin dans l'onglet "qui somme nous")
