### ISSUE TITLE
Déroulement de la prestation

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#5]
Dans le TITRE "Qui sommes-nous"
                   Sous-titre "déroulement de la prestation"

Il faut faire une section "important" et une section "article", comme pour les services

**Comment by jean-philippe-p** [comment]
j'ai ajouté une sous liste pour "qui sommes nous" dans le barre de menu, il y a 4 sous parties. et tu peux les éditer dans l'admin (check le texte car je suis pas sur d'avoir la dernière version)
