### ISSUE TITLE
sous-services dans la page de service

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#6]
je viens de me rappeler que l'organisation ne me plait pas pour les encadrés de sous-services quand tu es sur la page de service.

On a mis deux colonnes de blocs, je préfère que ce soit la même présentation que les services sur la page d’accueil. On en avait parlé mais je ne sais pas si tu as fait la modif ou pas encore

**Comment by jean-philippe-p** [comment]
t'es sûr ? je trouve ça classe avec deux colonne, j'pense que ça vaut le coup que tu demandes à plusieurs personnes pour voir ce qu'ils préfèrent.

**Comment by aurore-a** [comment]
D'accord, je fais un sondage et je te dis

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
