### ISSUE TITLE
encadrés "articles" et "important"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#7]
J'ai bien réfléchis, je ne trouve pas que ce soit très beau les encadrées.

Je suis un peu relou, désolé...

Est-ce que à la place on peut plutot faire dans ce genre : 
![image](https://user-images.githubusercontent.com/39243112/40484066-8f17be7e-5f5a-11e8-9678-c291e860ec9e.png)

Avec le section "important" sur la gauche, "articles" à droite avec le déroulé comme on avait dit 
(c'est mieux de mettre important à gauche parce que c'est toujours présent, alors que article non et du coup ça se verra moins je pense)

et pour le "tarif"
on peut le mettre comme sur l'image que je t'ai envoyé à la place du "contactez-nous" qu'ils ont mis eux, et ça renvoie directe à au "sous-titre" "tarif" de mon site ?

**Comment by jean-philippe-p** [comment]
je peux changer y a pas de soucis mais est ce que t'es sûr que ça aille avec le reste du design ? il faut avoir une vison globale de la page! je suis pas spécialements fan des encadrées non plus pour articles et important mais faut etre à peu près sur de ce que tu veux sinon on va changer tous les 4 matins. t'as pas vraiment d'outils adapté pour ça mais le bon vieux paint est ton ami ;)

**Comment by aurore-a** [comment]
Je suis sûr ! je crois ^^

non mais si, il vaut mieux comme ça, les encadrés finalement, ça rend pas bien, je ne trouve pas ça très joli alors que sur l'exemple ça fait plus serieux je trouve.

Du coup une section séparée en deux qui prend toute la largeur de page, mais je ne sais pas encore pour la couleur alors mets #666666 juste pour voir la démarcation. 

"Important" et "articles de Loi" ecrit en Julius Sans One 24px

Le petit encadré pour "Tarif" pas trop gros (sur l'exemple il est trop gros proportionnelement pour ce que je veux je pense) avec la même police, julius sans one en 24 px

**Comment by aurore-a** [comment]
j'ai les petits icones aussi à mettre, ceux que je voulais mettre dans un cercle au départ. 

Même présentation que sur l'exemple si possible 

![articles](https://user-images.githubusercontent.com/39243112/40485650-6ca2b36c-5f5f-11e8-9144-35377b6a1fd8.png)
![important](https://user-images.githubusercontent.com/39243112/40485668-74bbb6b6-5f5f-11e8-8531-3206cdbcefb8.png)

Ils ne se voient pas parce qu'ils sont blancs ! ^^

**Comment by jean-philippe-p** [comment]
ayé c'est carrément mieux comme ça :)
