### ISSUE TITLE
Encadré "contact"

### ISSUE THREAD

**Issue by aurore-a** [jean-philippe-p/callipolis#8]
Couleur : 

Fond encadré de contact #3A5555
texte contact #A3EEBA

Texte : 

"Votre demande concerne" à la place du texte "service"
"Informations supplémentaires sur votre situation" à la place de "informations"

**Comment by jean-philippe-p** [comment]
fait! par contre "Informations supplémentaires sur votre situation" tiens sur deux ligne du coup ça fait pas super joli je trouve
